#for mongo v5
version: '3'
services:
  mongo:
    image: mongo:5.0.0
#    container_name: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./mongo:/data/db
    environment:
      -MONGODB_DATABASE: nest-pokemon
#    networks:
#      - mongo


